/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export interface SentinelApiKeyUserMapping {
  api_key_hash: string;
  created_at: Generated<string | null>;
  deleted_at: string | null;
  source: string | null;
  user_id: number;
}

export interface SentinelAssistConfig {
  assist_channel_id: string | null;
  created_at: Generated<string>;
  guild_id: string | null;
  is_active: Generated<number>;
  ping_role_id: string | null;
  script_generation_role_ids: Generated<string>;
  updated_at: Generated<string>;
}

export interface SentinelAssistIpRateLimits {
  blocked_reason: string | null;
  blocked_until: string | null;
  error_type: string;
  first_occurrence_at: Generated<string>;
  id: Generated<number | null>;
  ip_address: string;
  is_blocked: Generated<number>;
  last_occurrence_at: Generated<string>;
  request_count: Generated<number>;
  request_path: string | null;
  user_agent: string | null;
  uuid: string | null;
}

export interface SentinelAssistScriptGenerationLimits {
  consecutive_failures: Generated<number>;
  created_at: Generated<string>;
  generation_count: Generated<number>;
  id: Generated<number | null>;
  is_rate_limited: Generated<number>;
  last_failure_at: string | null;
  last_generation_at: string | null;
  last_generation_ip: string | null;
  rate_limit_until: string | null;
  token_uuid: string;
  updated_at: Generated<string>;
}

export interface SentinelAssistTokens {
  blacklisted_at: string | null;
  blacklisted_reason: string | null;
  created_at: Generated<string>;
  discord_id: string;
  expires_at: string | null;
  guild_id: string;
  id: Generated<number | null>;
  is_active: Generated<number>;
  label: string | null;
  last_seen_ip: string | null;
  last_seen_user_agent: string | null;
  last_used_at: string | null;
  strike_count: Generated<number>;
  token_uuid: string;
  torn_id: number;
  updated_at: Generated<string>;
}

export interface SentinelBattlestatsSnapshots {
  created_at: Generated<string>;
  defense: number;
  dexterity: number;
  id: Generated<string | null>;
  speed: number;
  strength: number;
  total_stats: number;
}

export interface SentinelDestinationTravelTimes {
  airstrip: Generated<number>;
  airstrip_w_book: Generated<number>;
  bct: Generated<number>;
  bct_w_book: Generated<number>;
  destination_id: number;
  standard: Generated<number>;
  standard_cost: Generated<number>;
  standard_w_book: Generated<number>;
  wlt: Generated<number>;
  wlt_w_book: Generated<number>;
}

export interface SentinelFactionRoles {
  created_at: Generated<string>;
  enabled: Generated<number>;
  faction_id: number;
  faction_name: string | null;
  guild_id: string;
  id: string;
  leader_role_ids: Generated<string>;
  member_role_ids: Generated<string>;
  updated_at: Generated<string>;
}

export interface SentinelFinanceSettings {
  created_at: Generated<string>;
  min_reserve: Generated<number>;
  player_id: number;
  split_bookie: Generated<number>;
  split_gear: Generated<number>;
  split_training: Generated<number>;
  updated_at: Generated<string>;
}

export interface SentinelGuildApiKeys {
  api_key_encrypted: string;
  created_at: Generated<string | null>;
  deleted_at: string | null;
  guild_id: string;
  id: string;
  invalid_count: Generated<number | null>;
  is_primary: Generated<number | null>;
  last_invalid_at: string | null;
  last_used_at: string | null;
  provided_by: string;
  user_id: number;
}

export interface SentinelGuildAudit {
  action: string;
  actor_discord_id: string;
  created_at: Generated<string>;
  details: string | null;
  guild_id: string;
  id: string;
}

export interface SentinelGuildConfig {
  admin_role_ids: Generated<string | null>;
  auto_verify: Generated<number | null>;
  created_at: Generated<string>;
  enabled_modules: Generated<string | null>;
  faction_list_channel_id: string | null;
  faction_list_message_ids: string | null;
  guild_id: string;
  log_channel_id: string | null;
  nickname_template: Generated<string | null>;
  sync_interval_seconds: Generated<number | null>;
  tt_faction_ids: Generated<string | null>;
  tt_filtered_channel_id: string | null;
  tt_full_channel_id: string | null;
  tt_territory_ids: Generated<string | null>;
  updated_at: Generated<string>;
  verified_role_id: string | null;
  verified_role_ids: Generated<string | null>;
}

export interface SentinelGuildSyncJobs {
  created_at: Generated<string | null>;
  guild_id: string;
  in_progress: Generated<number | null>;
  last_sync_at: string | null;
  next_sync_at: Generated<string>;
  updated_at: Generated<string | null>;
}

export interface SentinelMapLabels {
  color_hex: string;
  created_at: Generated<string | null>;
  id: string | null;
  label_text: string;
  map_id: string;
}

export interface SentinelMaps {
  created_at: Generated<string | null>;
  created_by: string;
  guild_id: string;
  id: string | null;
  name: string;
  updated_at: Generated<string | null>;
}

export interface SentinelMapSessions {
  created_at: Generated<string | null>;
  expires_at: string;
  map_id: string;
  token: string | null;
  user_id: string;
}

export interface SentinelMapTerritories {
  label_id: string;
  map_id: string;
  territory_id: string;
}

export interface SentinelRacketTenure {
  created_at: Generated<string>;
  ended_at: number | null;
  faction_id: number;
  id: string | null;
  racket_name: string;
  reward: string;
  started_at: number;
  territory_id: string;
  updated_at: Generated<string>;
}

export interface SentinelRateLimitRequestsPerUser {
  api_key_hash: string;
  id: string;
  requested_at: Generated<string>;
  user_id: number | null;
}

export interface SentinelReactionRoleConfig {
  allowed_role_ids: Generated<string | null>;
  created_at: Generated<string | null>;
  guild_id: string;
  updated_at: Generated<string | null>;
}

export interface SentinelReactionRoleMappings {
  created_at: Generated<string | null>;
  emoji: string;
  id: number;
  message_id: string;
  role_id: string;
}

export interface SentinelReactionRoleMessages {
  channel_id: string;
  created_at: Generated<string | null>;
  description: string | null;
  guild_id: string;
  id: number;
  message_id: string;
  title: string;
  updated_at: Generated<string | null>;
}

export interface SentinelReviveConfig {
  created_at: Generated<string>;
  guild_id: string;
  min_hospital_seconds_left: Generated<number>;
  ping_role_id: string | null;
  request_channel_id: string | null;
  request_message_id: string | null;
  requests_output_channel_id: string | null;
  updated_at: Generated<string>;
}

export interface SentinelReviveRequests {
  cancelled_at: string | null;
  completed_at: string | null;
  completed_by_discord_id: string | null;
  created_at: Generated<string>;
  expires_at: string;
  faction_id: number | null;
  guild_id: string;
  hospital_seconds_left: number | null;
  hospital_until: number | null;
  id: number;
  last_action_relative: string | null;
  last_action_status: string | null;
  last_action_timestamp: number | null;
  request_channel_id: string | null;
  request_message_id: string | null;
  requester_discord_id: string;
  requester_torn_id: number | null;
  requester_torn_name: string | null;
  revivable: number | null;
  state: Generated<string>;
  status_description: string | null;
  status_details: string | null;
  status_state: string | null;
  updated_at: Generated<string>;
}

export interface SentinelSchemaMigrations {
  applied_at: Generated<string>;
  checksum: string;
  filename: string;
  id: string | null;
}

export interface SentinelStatBuildConfigurations {
  build_id: string;
  created_at: Generated<string>;
  defense_percentage: number | null;
  defense_value: number;
  dexterity_percentage: number | null;
  dexterity_value: number;
  id: string;
  main_stat: string;
  notes: string | null;
  speed_percentage: number | null;
  speed_value: number;
  strength_percentage: number | null;
  strength_value: number;
}

export interface SentinelStatBuilds {
  created_at: Generated<string>;
  description: string | null;
  id: string;
  name: string;
  notes: string | null;
  slug: string;
}

export interface SentinelSystemApiKeys {
  api_key_encrypted: string;
  api_key_hash: string | null;
  created_at: Generated<string | null>;
  deleted_at: string | null;
  id: string;
  invalid_count: Generated<number | null>;
  is_primary: Generated<number | null>;
  key_type: Generated<string | null>;
  last_invalid_at: string | null;
  last_used_at: string | null;
  user_id: number;
}

export interface SentinelTerritoryBlueprint {
  coordinate_x: number;
  coordinate_y: number;
  created_at: Generated<string | null>;
  density: number;
  id: string | null;
  neighbors: Generated<string>;
  respect: number;
  sector: number;
  size: number;
  slots: number;
  updated_at: Generated<string | null>;
}

export interface SentinelTerritoryState {
  created_at: Generated<string | null>;
  faction_id: number | null;
  is_warring: Generated<number | null>;
  racket_changed_at: number | null;
  racket_created_at: number | null;
  racket_level: number | null;
  racket_name: string | null;
  racket_reward: string | null;
  territory_id: string | null;
  updated_at: Generated<string | null>;
}

export interface SentinelTornCategories {
  created_at: Generated<string>;
  id: number;
  name: string;
}

export interface SentinelTornDestinations {
  country_code: string | null;
  id: number;
  name: string;
}

export interface SentinelTornFactions {
  best_chain: number | null;
  capacity: number;
  co_leader_id: number | null;
  created_at: Generated<string | null>;
  days_old: number | null;
  id: Generated<number | null>;
  is_enlisted: number | null;
  leader_id: number | null;
  members: number;
  name: string;
  note: string | null;
  rank: string | null;
  respect: number;
  tag: string;
  tag_image: string | null;
  updated_at: Generated<string | null>;
}

export interface SentinelTornGyms {
  created_at: Generated<string | null>;
  defense: number;
  dexterity: number;
  energy: number;
  id: Generated<number | null>;
  name: string;
  speed: number;
  strength: number;
  unlocked: Generated<number | null>;
  updated_at: Generated<string | null>;
}

export interface SentinelTornItems {
  booster_cooldown_hours: Generated<number | null>;
  category_id: number | null;
  cooldown: string | null;
  effect: string | null;
  energy_gain: Generated<number | null>;
  happy_gain: Generated<number | null>;
  image: string | null;
  item_id: Generated<number | null>;
  name: string;
  type: string | null;
  value: number | null;
}

export interface SentinelTrainingRecommendations {
  best_method_id: number | null;
  best_method_type: string | null;
  better_gym_bonus: number | null;
  better_gym_name: string | null;
  cost_per_stat: number;
  created_at: Generated<string>;
  current_gym_bonus: number | null;
  current_gym_sub_optimal: number | null;
  estimated_gains_per_train: number | null;
  id: Generated<string | null>;
  is_main_stat_focus: Generated<number | null>;
  max_quantity_affordable: Generated<number>;
  priority_score: Generated<number | null>;
  stat: string | null;
  training_budget: number | null;
}

export interface SentinelTravelData {
  active_travel_book: Generated<number>;
  capacity: Generated<number | null>;
  has_airstrip: Generated<number>;
  has_wlt_benefit: Generated<number>;
  player_id: number;
  travel_arrival_at: string | null;
  travel_departed_at: string | null;
  travel_destination: string | null;
  travel_method: string | null;
  travel_time_left: number | null;
  updated_at: Generated<string>;
}

export interface SentinelTravelRecommendations {
  best_item_id: number | null;
  cash_to_carry: number | null;
  destination_id: number;
  id: string;
  message: string | null;
  profit_per_minute: number | null;
  profit_per_trip: number | null;
  recommendation_rank: number | null;
  round_trip_minutes: number | null;
  updated_at: Generated<string>;
  user_id: string;
}

export interface SentinelTravelSettings {
  alert_cooldown_minutes: Generated<number>;
  alerts_enabled: Generated<number>;
  blacklisted_categories: Generated<string | null>;
  blacklisted_items: Generated<string | null>;
  created_at: Generated<string>;
  last_alert_sent: string | null;
  min_profit_per_minute: number | null;
  min_profit_per_trip: number | null;
  updated_at: Generated<string>;
  user_id: string;
}

export interface SentinelTravelStockCache {
  cost: number;
  destination_id: number;
  id: number;
  ingested_at: Generated<string>;
  item_id: number;
  last_updated: Generated<string>;
  quantity: number;
}

export interface SentinelTtConfig {
  created_at: Generated<string | null>;
  faction_ids: Generated<string | null>;
  guild_id: string;
  notification_type: Generated<string>;
  territory_ids: Generated<string | null>;
  updated_at: Generated<string | null>;
}

export interface SentinelUserAlerts {
  created_at: Generated<string>;
  last_alert_data: string | null;
  last_alert_sent_at: string | null;
  module: string;
  updated_at: Generated<string>;
  user_id: string;
}

export interface SentinelUserBars {
  energy_current: Generated<number>;
  energy_flat_time_to_full: number | null;
  energy_maximum: Generated<number>;
  energy_time_to_full: number | null;
  happy_current: Generated<number>;
  happy_maximum: Generated<number>;
  life_current: Generated<number>;
  life_maximum: Generated<number>;
  nerve_current: Generated<number>;
  nerve_flat_time_to_full: number | null;
  nerve_maximum: Generated<number>;
  nerve_time_to_full: number | null;
  updated_at: Generated<string>;
  user_id: string;
}

export interface SentinelUserBuildPreferences {
  build_id: string;
  created_at: Generated<string>;
  id: string;
  main_stat: string;
  updated_at: Generated<string>;
}

export interface SentinelUserCooldowns {
  booster: Generated<number>;
  drug: Generated<number>;
  medical: Generated<number>;
  updated_at: Generated<string>;
  user_id: string;
}

export interface SentinelUserData {
  is_donator: Generated<number>;
  name: string | null;
  player_id: Generated<number | null>;
  profile_image: string | null;
  updated_at: Generated<string>;
}

export interface SentinelUsers {
  api_key: string;
  created_at: Generated<string>;
  updated_at: Generated<string>;
  user_id: string;
}

export interface SentinelUserSnapshots {
  active_gym: number | null;
  bookie_updated_at: string | null;
  bookie_value: number | null;
  booster_cooldown: Generated<number | null>;
  can_boost_energy_perk: Generated<number | null>;
  chain_current: Generated<number | null>;
  chain_flat_time_to_full: number | null;
  chain_maximum: Generated<number | null>;
  created_at: Generated<string>;
  drug_cooldown: Generated<number | null>;
  energy_current: Generated<number | null>;
  energy_flat_time_to_full: number | null;
  energy_maximum: Generated<number | null>;
  energy_time_to_full: number | null;
  happy_current: Generated<number | null>;
  happy_flat_time_to_full: number | null;
  happy_maximum: Generated<number | null>;
  id: Generated<string | null>;
  life_current: Generated<number | null>;
  life_flat_time_to_full: number | null;
  life_maximum: Generated<number | null>;
  liquid_cash: number | null;
  medical_cooldown: Generated<number | null>;
  nerve_current: Generated<number | null>;
  nerve_flat_time_to_full: number | null;
  nerve_maximum: Generated<number | null>;
  nerve_time_to_full: number | null;
  net_worth: number | null;
}

export interface SentinelVerifiedUsers {
  created_at: Generated<string>;
  discord_id: string;
  faction_id: number | null;
  faction_tag: string | null;
  torn_id: number;
  torn_name: string;
  updated_at: Generated<string>;
}

export interface SentinelWarLedger {
  assaulting_faction: number;
  created_at: Generated<string | null>;
  defending_faction: number;
  end_time: string | null;
  start_time: string;
  territory_id: string;
  updated_at: Generated<string | null>;
  victor_faction: number | null;
  war_id: Generated<number | null>;
}

export interface SentinelWarTrackers {
  channel_id: string | null;
  created_at: Generated<string | null>;
  enemy_side: string;
  guild_id: string;
  id: string;
  message_id: string | null;
  min_away_minutes: Generated<number>;
  territory_id: string;
  updated_at: Generated<string | null>;
  war_id: number;
}

export interface SentinelWorkerLogs {
  created_at: Generated<string>;
  duration_ms: number | null;
  error_message: string | null;
  id: string;
  is_limited: Generated<number | null>;
  last_error_at: string | null;
  limited_until: string | null;
  message: string | null;
  run_finished_at: string | null;
  run_started_at: Generated<string>;
  status: string;
  worker_id: string;
}

export interface SentinelWorkers {
  created_at: Generated<string>;
  id: string;
  name: string;
  updated_at: Generated<string>;
}

export interface SentinelWorkerSchedules {
  attempts: Generated<number>;
  backoff_until: string | null;
  cadence_seconds: number;
  created_at: Generated<string | null>;
  enabled: Generated<number>;
  force_run: Generated<number>;
  last_run_at: string | null;
  metadata: Generated<string | null>;
  next_run_at: string;
  updated_at: Generated<string | null>;
  worker_id: string;
}

export interface DB {
  sentinel_api_key_user_mapping: SentinelApiKeyUserMapping;
  sentinel_assist_config: SentinelAssistConfig;
  sentinel_assist_ip_rate_limits: SentinelAssistIpRateLimits;
  sentinel_assist_script_generation_limits: SentinelAssistScriptGenerationLimits;
  sentinel_assist_tokens: SentinelAssistTokens;
  sentinel_battlestats_snapshots: SentinelBattlestatsSnapshots;
  sentinel_destination_travel_times: SentinelDestinationTravelTimes;
  sentinel_faction_roles: SentinelFactionRoles;
  sentinel_finance_settings: SentinelFinanceSettings;
  sentinel_guild_api_keys: SentinelGuildApiKeys;
  sentinel_guild_audit: SentinelGuildAudit;
  sentinel_guild_config: SentinelGuildConfig;
  sentinel_guild_sync_jobs: SentinelGuildSyncJobs;
  sentinel_map_labels: SentinelMapLabels;
  sentinel_map_sessions: SentinelMapSessions;
  sentinel_map_territories: SentinelMapTerritories;
  sentinel_maps: SentinelMaps;
  sentinel_racket_tenure: SentinelRacketTenure;
  sentinel_rate_limit_requests_per_user: SentinelRateLimitRequestsPerUser;
  sentinel_reaction_role_config: SentinelReactionRoleConfig;
  sentinel_reaction_role_mappings: SentinelReactionRoleMappings;
  sentinel_reaction_role_messages: SentinelReactionRoleMessages;
  sentinel_revive_config: SentinelReviveConfig;
  sentinel_revive_requests: SentinelReviveRequests;
  sentinel_schema_migrations: SentinelSchemaMigrations;
  sentinel_stat_build_configurations: SentinelStatBuildConfigurations;
  sentinel_stat_builds: SentinelStatBuilds;
  sentinel_system_api_keys: SentinelSystemApiKeys;
  sentinel_territory_blueprint: SentinelTerritoryBlueprint;
  sentinel_territory_state: SentinelTerritoryState;
  sentinel_torn_categories: SentinelTornCategories;
  sentinel_torn_destinations: SentinelTornDestinations;
  sentinel_torn_factions: SentinelTornFactions;
  sentinel_torn_gyms: SentinelTornGyms;
  sentinel_torn_items: SentinelTornItems;
  sentinel_training_recommendations: SentinelTrainingRecommendations;
  sentinel_travel_data: SentinelTravelData;
  sentinel_travel_recommendations: SentinelTravelRecommendations;
  sentinel_travel_settings: SentinelTravelSettings;
  sentinel_travel_stock_cache: SentinelTravelStockCache;
  sentinel_tt_config: SentinelTtConfig;
  sentinel_user_alerts: SentinelUserAlerts;
  sentinel_user_bars: SentinelUserBars;
  sentinel_user_build_preferences: SentinelUserBuildPreferences;
  sentinel_user_cooldowns: SentinelUserCooldowns;
  sentinel_user_data: SentinelUserData;
  sentinel_user_snapshots: SentinelUserSnapshots;
  sentinel_users: SentinelUsers;
  sentinel_verified_users: SentinelVerifiedUsers;
  sentinel_war_ledger: SentinelWarLedger;
  sentinel_war_trackers: SentinelWarTrackers;
  sentinel_worker_logs: SentinelWorkerLogs;
  sentinel_worker_schedules: SentinelWorkerSchedules;
  sentinel_workers: SentinelWorkers;
}
