packages:
  - packages/*
  - apps/*

allowBuilds:
  "@prisma/client": true
  "@prisma/engines": true
  better-sqlite3: false
  esbuild: true
  msw: false
  prisma: true
  sharp: true
  unrs-resolver: true
  workerd: true

ignoredBuiltDependencies:
  - sharp
  - unrs-resolver
  - better-sqlite3

onlyBuiltDependencies:
  - esbuild
  - workerd

overrides:
  typescript: "^5.9.3"
